Milestone: Style bookstore
Gleennkar/book_store pull request #5
Opened 2022-11-13 00:16 UTC by Gleennkar

## Added style to the bookstore app
- Check linter errors
- Added style 
- Updated my README.md

2022-11-13 01:55 UTC, vickymarz requested changes
Hi @Gleennkar, 

You have done a great job so far! 💪 👏
You still need to work on a few issues before moving on to the next project, but you're almost there!

## Top highlight 🎯

- The Pull Request is following the GitHub Flow ✅  
- The PR title and description are professional and descriptive ✅ 
- The commit messages are meaningful ✅ 
- Linters are working properly ✅ 


## Required Changes ♻️
_Check the comments under the review._
<img src="https://media2.giphy.com/media/Jq824R93JsLwZCaiSL/giphy.gif"/>

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:

N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-13 01:55 UTC, vickymarz commented on src/components/Books.js
> +          <div className="d-flex mt-3 book" key={uuidv4()}>
- [ ] Kindly ensure that your bookstore book styling exactly matches the design you are given. Kindly add all the missing parts such as the progress bar 👍🏽.

Zeplin design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/201501759-2d30a0a2-322f-4855-8a94-29106f6b8904.png)

Your design 👇🏽 
![image](https://user-images.githubusercontent.com/63473584/201501787-94fd635c-e967-45fd-9287-969d21dcab84.png)

2022-11-13 04:40 UTC, tufoinnkuo10 requested changes
Hi @Gleennkar 

There are some issues that you still need to work on to go to the next project but you are almost there!

To Highlight
✅ You used the correct Github flow
✅ Descriptive pull request message
✅ linter error checks validated
✅ Documented your work professionally

Required Changes ♻️
Check the comments under the review
Optional suggestions
_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise.
As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using this [form.](https://airtable.com/shrQAqnBwek5a0O0s)

2022-11-13 04:40 UTC, tufoinnkuo10 commented on src/components/Books.js
> +          <div className="d-flex mt-3 book" key={uuidv4()}>
- [ ] like the previous reviewer noted, Kindly add all the missing parts such as the progress bar so it matches the Zeplin design 👍🏽.

2022-11-13 06:08 UTC, rotimiazeez requested changes
# Hi @Gleennkar  😉, 
## Great work on making the changes 👏 
You've done well implementing some of the requested changes, but there are still some which aren't been addressed yet.
### To Highlight 👇🏽
- No Linter error ✔️ 
- Good PR description 👍🏽 
- Good commit message(s) 😉


## Suggested changes
_Check the comments under the review._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me(@rotimiazeez) in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid, unless it is requested otherwise._**

2022-11-13 06:08 UTC, rotimiazeez commented on src/index.css
> +}
- Please note that your design does not match the original Zeplin design. Kindly make sure your design looks similar (font, color, margin, etc.) before submitting again. 😉
- Original Design
![git](https://user-images.githubusercontent.com/44624138/201508190-d979fcee-8223-4783-a9ee-c19120a2de15.png)
- Your Design
![Screenshot from 2022-11-13 06-58-06](https://user-images.githubusercontent.com/44624138/201508216-83ad8999-fa20-492f-ac19-586707e6efed.png)

2022-11-15 08:56 UTC, bellom commented
@Gleennkar, 

### This is a manual review

According to the project requirement, **your design should match the design on Zeplin.**
<img width="516" alt="image" src="https://user-images.githubusercontent.com/31897434/201870936-75ad107b-c7fa-450d-bce5-c423be1c0677.png">

As stated in the project requirement, **kindly use the information detailed in Zeplin to style your website.**
For example: look at the properties for `Action` in the screenshot below;
<img width="1569" alt="image" src="https://user-images.githubusercontent.com/31897434/201871644-ad14ae61-4a42-47e6-8d7b-e91ce4952b13.png">


Your design:
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/31897434/201874324-3d87eedf-c141-423c-847b-3a259c86f215.png">


I hope this is helpful.

2022-11-15 10:37 UTC, julie-ify approved these changes
Hi @Gleennkar,

## Highlights!
- Good feature branch name ✔️ 
- No linter errors ✔️ 
- Descriptive pull request ✔️ 
- Descriptive commit messages ✔️ 
- Good code organization and working app ✔️
- Descriptive README ✔️ 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

# Status: Approved ✔️ 

Cheers and Happy coding!👏👏👏

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._


Feel free to leave any questions or comments in the PR thread if something is not 100% clear.


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-11-15 12:11 UTC, merged